class AppStrings{
  static String appname = "doctorsAppointment",
     bestDocapp = "Best Doctor\n Appointment App",
     welcomeBack = "Welcome back",
     weAreExcited = "We are excited to have you back!",
     signupNow = "Sign up now and start exploring all that our app has to offer.",
     email = "Email",
     emailHint = "Enter your email.....",
     password = "Password",
     passwordHint = "Enter your password here......",
     fullName = "Full Name",
      fullNameHint = "Enter your name here....",
     confirmPassword = "Confirm Password",
     forgetPassword = "Forget Password?",
     login = "Login",
     signup = "Signup",
      welcome = "Welcome",
      search ="Search doctor",
     alreadyHaveAccount = "Already have ancount?",
     dontHaveAccount = "Don't have an account?";
}