// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxkjqprROS0fhDLtsBVkbZYNe8KXqHS6w',
    appId: '1:972507236381:web:3e25fa84513477d1b55ef4',
    messagingSenderId: '972507236381',
    projectId: 'doctors-appointment-28',
    authDomain: 'doctors-appointment-28.firebaseapp.com',
    storageBucket: 'doctors-appointment-28.appspot.com',
    measurementId: 'G-Y8G374NGLP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEz-4noWZ9cfCR3HL595lHw2eOSO2hc-k',
    appId: '1:972507236381:android:ca2f049adcea474cb55ef4',
    messagingSenderId: '972507236381',
    projectId: 'doctors-appointment-28',
    storageBucket: 'doctors-appointment-28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoJnwJGxqdG4pRF41N5v45Hv41zXzGlO0',
    appId: '1:972507236381:ios:414becc0c8639b62b55ef4',
    messagingSenderId: '972507236381',
    projectId: 'doctors-appointment-28',
    storageBucket: 'doctors-appointment-28.appspot.com',
    iosBundleId: 'com.abraham.doctorsAppt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoJnwJGxqdG4pRF41N5v45Hv41zXzGlO0',
    appId: '1:972507236381:ios:21a937b42296a3e7b55ef4',
    messagingSenderId: '972507236381',
    projectId: 'doctors-appointment-28',
    storageBucket: 'doctors-appointment-28.appspot.com',
    iosBundleId: 'com.abraham.doctorsAppt.RunnerTests',
  );
}
